-- LABORATORIO EDUCATIVO SEMANA 3
-- Ejecutar completo en Supabase > SQL Editor.
-- No almacena nombres, correos, contraseñas, IP, ubicación ni identificadores de dispositivo.

create table if not exists public.sesiones (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nombre text not null,
  activa boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.respuestas (
  id bigint generated by default as identity primary key,
  sesion_id bigint not null references public.sesiones(id) on delete cascade,
  codigo text not null check (codigo ~ '^[A-Z0-9-]{2,12}$'),
  carrera text not null check (char_length(carrera) between 2 and 80),
  created_at timestamptz not null default now(),
  unique (sesion_id, codigo)
);

alter table public.sesiones enable row level security;
alter table public.respuestas enable row level security;

-- Reiniciar políticas si ejecutas el script nuevamente.
drop policy if exists "Sesion publica visible" on public.sesiones;
drop policy if exists "Insertar respuesta solo en sesion activa" on public.respuestas;
drop policy if exists "Resultados visibles para demo" on public.respuestas;

-- El navegador puede conocer solo el estado de la sesión.
create policy "Sesion publica visible"
on public.sesiones for select
to anon
using (true);

-- Permite insertar únicamente si la sesión asociada está activa.
create policy "Insertar respuesta solo en sesion activa"
on public.respuestas for insert
to anon
with check (
  exists (
    select 1 from public.sesiones s
    where s.id = sesion_id and s.activa = true
  )
);

-- Para este laboratorio temporal, el panel docente público puede leer los resultados ficticios.
-- IMPORTANTE: los datos deben ser ficticios. Si deseas reutilizarlo con datos reales,
-- elimina esta política y protege profesor.html con Supabase Auth.
create policy "Resultados visibles para demo"
on public.respuestas for select
to anon
using (true);

insert into public.sesiones (slug,nombre,activa)
values ('semana-3-2026','Simulación controlada · Semana 3',false)
on conflict (slug) do update set nombre=excluded.nombre;

-- PARA ABRIR LA ACTIVIDAD ANTES DE LA CLASE:
-- update public.sesiones set activa=true where slug='semana-3-2026';

-- PARA CERRARLA DESPUÉS DE 3 MINUTOS:
-- update public.sesiones set activa=false where slug='semana-3-2026';

-- PARA LIMPIAR RESPUESTAS ANTES DE UNA NUEVA PRUEBA:
-- delete from public.respuestas
-- where sesion_id=(select id from public.sesiones where slug='semana-3-2026');
